//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatrizCapFgiEntities : DbContext
    {
        public MatrizCapFgiEntities()
            : base("name=MatrizCapFgiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_causa_baja> cat_causa_baja { get; set; }
        public virtual DbSet<cat_generos> cat_generos { get; set; }
        public virtual DbSet<cat_horarios> cat_horarios { get; set; }
        public virtual DbSet<cat_status> cat_status { get; set; }
        public virtual DbSet<cat_tipousuario> cat_tipousuario { get; set; }
        public virtual DbSet<tbl_alcaldias> tbl_alcaldias { get; set; }
        public virtual DbSet<tbl_areas> tbl_areas { get; set; }
        public virtual DbSet<tbl_colaboradores> tbl_colaboradores { get; set; }
        public virtual DbSet<tbl_cursoexterno> tbl_cursoexterno { get; set; }
        public virtual DbSet<tbl_cursointerno> tbl_cursointerno { get; set; }
        public virtual DbSet<tbl_departamentos> tbl_departamentos { get; set; }
        public virtual DbSet<tbl_pno> tbl_pno { get; set; }
        public virtual DbSet<tbl_puestos> tbl_puestos { get; set; }
        public virtual DbSet<tbl_sucursales> tbl_sucursales { get; set; }
        public virtual DbSet<tbl_usuarios> tbl_usuarios { get; set; }
    }
}
