//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_puestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_puestos()
        {
            this.tbl_colaboradores = new HashSet<tbl_colaboradores>();
        }
    
        public int Id_Puesto { get; set; }
        public int Id_Departamento { get; set; }
        public int Id_Area { get; set; }
        public string Nombre { get; set; }
        public string Comentarios { get; set; }
        public string Observaciones { get; set; }
    
        public virtual tbl_areas tbl_areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_colaboradores> tbl_colaboradores { get; set; }
        public virtual tbl_departamentos tbl_departamentos { get; set; }
    }
}
