//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuarios
    {
        public int Id_Usuario { get; set; }
        public int Numero_Empleado { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public int Id_TipoUsuario { get; set; }
        public Nullable<int> Id_Area { get; set; }
    }
}
