//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pno
    {
        public int Id_PNO { get; set; }
        public string Nombre_PNO { get; set; }
        public Nullable<System.DateTime> Fecha_PNO { get; set; }
        public string Duracion_PNO { get; set; }
        public string Facilitador_PNO { get; set; }
        public string Comentarios_PNO { get; set; }
        public string Observaciones_PNO { get; set; }
    }
}
