//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cursoexterno
    {
        public int Id_CE { get; set; }
        public string Nombre_CE { get; set; }
        public string Tipo_Evento_CE { get; set; }
        public string Objetivo_CE { get; set; }
        public string Justificacion_CE { get; set; }
        public string Finalidad_CE { get; set; }
        public Nullable<System.DateTime> Fecha_CE { get; set; }
        public string Horario_CE { get; set; }
        public string Sede_CE { get; set; }
        public string Nombre_Institucion_CE { get; set; }
        public string Razon_Social_CE { get; set; }
        public string RFC_CE { get; set; }
        public string Direccion_Fiscal_CE { get; set; }
        public string Instructor_CE { get; set; }
        public string Registro_STPS_CE { get; set; }
        public Nullable<decimal> Importe_CE { get; set; }
        public Nullable<decimal> IVA_CE { get; set; }
        public Nullable<decimal> Total_CE { get; set; }
        public string Banco_CE { get; set; }
        public Nullable<long> Cuenta_CE { get; set; }
        public Nullable<long> Clabe_CE { get; set; }
        public string Comentarios_CE { get; set; }
        public string Observaciones_CE { get; set; }
    }
}
