//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cursointerno
    {
        public int Id_CI { get; set; }
        public string Nombre_CI { get; set; }
        public string Tipo_Evento_CI { get; set; }
        public Nullable<System.DateTime> Fecha_CI { get; set; }
        public string Duracion_CI { get; set; }
        public string Facilitador_CI { get; set; }
        public string Comentarios_CI { get; set; }
        public string Observaciones_CI { get; set; }
    }
}
