//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_de_capacitación
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_colaboradores
    {
        public int Numero_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Departamento { get; set; }
        public Nullable<int> Id_Puesto { get; set; }
        public Nullable<int> Id_Alcaldia { get; set; }
        public Nullable<int> Id_Sucursal { get; set; }
        public string Horario { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string RFC { get; set; }
        public string Curp { get; set; }
        public string Num_SS { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso_Plubek { get; set; }
        public string Status_Tab { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public Nullable<int> Id_Causa_Baja { get; set; }
        public string Comentarios { get; set; }
        public string Comentarios_2 { get; set; }
        public string Observaciones { get; set; }
    
        public virtual cat_causa_baja cat_causa_baja { get; set; }
        public virtual tbl_alcaldias tbl_alcaldias { get; set; }
        public virtual tbl_areas tbl_areas { get; set; }
        public virtual tbl_departamentos tbl_departamentos { get; set; }
        public virtual tbl_puestos tbl_puestos { get; set; }
        public virtual tbl_sucursales tbl_sucursales { get; set; }

    }
}
